### ISSUE TITLE
Implement Elixir

### ISSUE THREAD

**Issue by puredazzle** [wordplate/wordplate#114]
What are the thoughts on implementing [Elixir](https://github.com/laravel/elixir) as compiler for SASS/LESS and JavaScript? It uses Gulp for compiling.

**Comment by vinkla** [comment]
This is definitely something we should discuss. Good initiative!

**Comment by puredazzle** [comment]
Here is an example https://github.com/wordplate/wordplate/tree/elixir

**Comment by vinkla** [comment]
:+1:

**Comment by puredazzle** [comment]
Fixed in with this commit: https://github.com/wordplate/wordplate/commit/b64ab770b5321df2704fb8f3729eb0b2d4145cf4
