### ISSUE TITLE
Soil not working

### ISSUE THREAD

**Issue by puredazzle** [wordplate/wordplate#126]
[Soil](https://github.com/roots/soil) is not working at the moment. We need to figure out what has happened and if [Soil](https://github.com/roots/soil) is a good solution.

**Comment by vinkla** [comment]
Okay, no good. Maybe @QWp6t has an idea about this?

**Comment by puredazzle** [comment]
Seems like in their boilerplate they add Soil functions outside of `after_setup_theme`, see here: https://github.com/roots/sage/blob/master/functions.php

**Comment by vinkla** [comment]
Our implementation is just moved to the front instead of forcing developers to use it. Shouldn't have changed anything? Right?

**Comment by puredazzle** [comment]
Seems like Soil adds its own after_setup_theme-function so when we add it to our function it becomes double, for more information please see here: https://github.com/roots/soil/blob/master/soil.php#L55-L65

**Comment by vinkla** [comment]
Maybe we should move them to a init action instead of after_theme_setup then?

**Comment by puredazzle** [comment]
It doesn't matter, because then it would be like this:

```
add_action('init', function () {
     add_action('after_setup_theme', function () {
```

Because Soil adds their own setup function here: https://github.com/roots/soil/blob/master/soil.php#L55-L65

**Comment by vinkla** [comment]
Aah okay, then we just call them directly in the functions.php file?

**Comment by vinkla** [comment]
Just saw your PR, nevermind.

**Comment by puredazzle** [comment]
Now! Sorry for the fuzz

**Comment by vinkla** [comment]
No worries ;)
