### ISSUE TITLE
Import error on gulp step

### ISSUE THREAD

**Issue by RobertCalise** [wordplate/wordplate#133]
When I get to the stage in the install process when it's time to run gulp, I get the following error:

```
user@host:~$ gulp
[00:54:03] Failed to load external module babel-core/register
[00:54:03] Failed to load external module babel/register

/var/www/site/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import elixir fr
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
```

Any thoughts? I'm not familiar with Babel, and attempts to Google this have not proved fruitful.

Edit: Using the latest version of Wordplate.

**Comment by RobertCalise** [comment]
Update: I missed something on this particular machine - the npm version was out of date. Upgrading npm, deleting node_modules and then re-running npm install fixed the issue.

**Comment by vinkla** [comment]
Yeah, we've updated to use babel out of the box. Glad you solved it, maybe we should add the node requirement in the package.json just to make sure everyone can install it and get proper error messages. Let us know if you've any other errors and we'll try to help you out. Thanks for reporting.

**Comment by RobertCalise** [comment]
Appreciate it. Works like a charm, otherwise. Thanks for putting together a great package.

**Comment by vinkla** [comment]
Anytime! Let me know if there are any features you would like to see added or if you've any other feedback.

**Comment by RobertCalise** [comment]
Not sure if you'd prefer to discuss in a new thread, but I have two that I'm mulling over, actually. 

1. Using env() to set table prefix by default. The motivation here, of course, is not having to track config changes like this in your local repo, which causes you to ultimately diverge from Wordplate.
2. A method for adding "custom" config items. For example, I use the WP Offload S3/Amazon Web Services plugin, which encourage defining AWS keys in wp-config.php rather than saving in database. I'm reading them in with env(), but again, this requires adding lines to wp-config.php and committing to the repo. 

I suppose the easiest solution here would be untracking wp-config.php from git altogether, and just building it from wp-config-sample.php (which could be kept versioned) on new installs. Thoughts?

**Comment by vinkla** [comment]
No worries, we can discuss here.

1. Aren't we using `env()` today? Sorry but I'm not sure what you mean?
2. Maybe we could do like Laravel and create a services.php file which would contain some default config. In case you don't know (we haven't added this to the docs) you can actually add as many config files as you want. WordPlate will automagically find them and make em accessable through the `config()` helper method.

**Comment by vinkla** [comment]
I would suggest to only add `env()` to the wp-config.php file and don't commit any secret variables to the configuration.

**Comment by RobertCalise** [comment]
1. Yes, you're right. It's late and I missed that. Sorry.
2. Ah! That's an interesting concept. Is there documentation about this/a naming convention to follow?

And yes, I am only adding env() to wp-config.php and saving the actual values in .env, but adding the new lines with env() still requires a commit. Custom additional config files makes that a non-issue.

**Comment by vinkla** [comment]
There is no naming convention really, you can basically call them whatever you want. I usually just refer to the [Laravel setup](https://github.com/laravel/laravel/tree/master/config) for this. 

You mean it requires a commit to add stuff to the wp-config.php file? IMO I don't see any harm of adding custom info to the wp-config.php file. Of course it depends on what you're trying to achieve but defining constants within the wp-config.php is a good idea. Keeping it in one place :)

**Comment by RobertCalise** [comment]
I just dislike deviations from the source repository as a personal preference. Wordplate may be an exception, since it's primarily intended as an installation tool, but it sucks updating your codebase from the source repo and having conflicts/things overwritten/having to redo them, even if it only ever happens once or twice. ;)

**Comment by vinkla** [comment]
Yeah, I totally agree with you but I don't see a way around it. I usually do this with most PHP frameworks when there is a new major version available. It takes time but it is often worth the effort.
