### ISSUE TITLE
Better support for multisites

### ISSUE THREAD

**Issue by frozzare** [wordplate/wordplate#134]
Would be nice if you could turn off/on multisites in a config file.

**Comment by vinkla** [comment]
I like the idea, what do we need to do in the framework?

**Comment by frozzare** [comment]
I think the first step is to have a configuration for turning on the multisites installation.

```php
/* Multisite */
define( 'WP_ALLOW_MULTISITE', true );
```

Then you have to install your network, see http://codex.wordpress.org/Create_A_Network#Step_3:_Installing_a_Network

After that there is a couple of configurations needed in your `wp-config.php`, something like this for directories installation (you can tell wp to use subdomains instead)

```php
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', false );
define( 'DOMAIN_CURRENT_SITE', getenv( 'DOMAIN_CURRENT_SITE' ) );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
``` 

I'm not sure about how this should be implemented since you can configure a multisites in different ways.

**Comment by vinkla** [comment]
Yeah, maybe we can create a `multisite.php` file specific for those settings. The `WP_ALLOW_MULTISITE` constant will control the other constants I guess? If the `WP_ALLOW_MULTISITE`  isn't is set to true then we shouldn't care about multisite?

**Comment by frozzare** [comment]
`WP_ALLOW_MULTISITE` is only needed to turn on the installation page. `MULTISITE` is used to tell that the wp site is running multisites.

**Comment by vinkla** [comment]
Okay, I see. If you feel up to it maybe we can start working on a PR.

**Comment by frozzare** [comment]
I think it's better that someone that works with WordPlate daily (or using it in their work) is doing this, I just think it's a good idea to offer configuration for this in a WordPress framework.

So maybe if you have a label for `help wanted` or something like that I think it's good to add it to this issue.

**Comment by vinkla** [comment]
Yeah, lets just keep it here.

**Comment by vinkla** [comment]
This is now addressed.

**Comment by amenk** [comment]
What exactly was added? Is multisite setup simplified now? Where can I find documentation?

**Comment by amenk** [comment]
I found https://github.com/wordplate/multisite but it is deprecated ... what is the suggested way to use multisite? Or is it unsupported? If latter, why?

**Comment by vinkla** [comment]
@amenk There isn't a official WordPlate setup for multisite but you can [follow the default WordPress](https://codex.wordpress.org/Create_A_Network) guide and add the configuration before `$application->run()` in the `wp-config.php` file.

**Comment by amenk** [comment]
Yes, but URLs seem to get still messed up.
Was the that the reason to not support it anymore, because it is to buggy? Or why is the module deprecated?

**Comment by vinkla** [comment]
> Was the that the reason to not support it anymore, because it is to buggy? 

> Or why is the module deprecated?

The reason

**Comment by vinkla** [comment]
> Was the that the reason to not support it anymore, because it is to buggy? 

WordPlate supports multisite. Just follow the guide I posted in the comment above.

> Or why is the module deprecated?

We tried to simplify the process of setting up multisite but we just made it more confusing to be honest. Setting up a multisite isn't easy with WordPress to begin with and we didn't want to maintain the plugin if it wasn't easy to setup.

**Comment by amenk** [comment]
I pretty much did that but will try again. Are we talking about multisite on subdomains, multisite in subfolders or should both be supported?

**Comment by amenk** [comment]
Okay, all seems to work. Probably I added the `define()` at the wrong place before.

1. followed the multi site steps
2. replaced the full .htaccess

Thanks and sorry for the noise ;-)

**Comment by vinkla** [comment]
> Thanks and sorry for the noise ;-)

No worries, glad it worked out :)
