### ISSUE TITLE
Config for wordpress installation path

### ISSUE THREAD

**Issue by frozzare** [wordplate/wordplate#135]
It's hardcoded today, would be nice if we could change this in the configuration files.

**Comment by vinkla** [comment]
Which path are you referring to? The `public/wordpress` path?

**Comment by frozzare** [comment]
Yes.

**Comment by vinkla** [comment]
It is configureable right now? 

1. https://github.com/wordplate/wordplate/blob/master/composer.json#L31
2. https://github.com/wordplate/wordplate/blob/master/public/wp-config.php#L37-L41

Or do you mean in the configuration files?

**Comment by frozzare** [comment]
I mean in the configuration files since they exists :)

**Comment by vinkla** [comment]
Yeah, I'm not sure how we're going to do that since we have to update the path in the composer.json file. Any ideas?

**Comment by frozzare** [comment]
I don't think you need to have config files for the composer file, but since most of the wp configuration is in `.env` or configuration files it would be nice the have the wordpress path there as well. 

In the `wp-config.php` the hardcoded wordpress path exists on two lines.

```php
define('WP_SITEURL', WP_HOME.'/wordpress');
```

and 

```php
define('ABSPATH', __DIR__.'/wordpress');
```

As of right now you have to change the path 3 times.

**Comment by vinkla** [comment]
We've removed the config and this is now up to the developer. Thanks for your suggestion.
