### ISSUE TITLE
Better documentation ?

### ISSUE THREAD

**Issue by ligne13** [wordplate/wordplate#141]
Hi,
do you plan on writing a more detailed documentation ?
thanks

**Comment by vinkla** [comment]
Let me know what you want to see in the docs and then we can add it.

**Comment by vinkla** [comment]
@ligne13 please let us know what you're missing.

**Comment by ligne13** [comment]
Hi @vinkla ,
sorry for the late answer. I finally choose another solution (roots.io's bedrock), but will have a look on the future of WordPlate which seems a challenging alternative.
About the docs,  WordPlate could have something similar to Bedrock, explaining the folder structure, the packages used, some best practices to start an app.

**Comment by vinkla** [comment]
@ligne13 okay, thanks for getting back. We'll look into to it.
