### ISSUE TITLE
Media uploaded was being renamed

### ISSUE THREAD

**Issue by seerjun** [wordplate/wordplate#144]
For eg, I uploaded an image named "why.png". But it was renamed to "434710f0-1677-43fc-b9d2-b7f9e8214860.png". Am I miss out any env config setting?

**Comment by vinkla** [comment]
This is what the `wordplate/uuid` plugin does. It replaces both filenames and the `guid` column in the database. Thanks for pointing out that this isn't clear. I'll remove the uuid plugin by default and then developers can opt it in.

**Comment by vinkla** [comment]
If you don't want this behaviour then you can remove the `wordplate/uuid` from your `composer.json` file.
