### ISSUE TITLE
WooCommerce compatibility

### ISSUE THREAD

**Issue by nathanaelphilip** [wordplate/wordplate#145]
when running the WooCommerce setup script, it throws an error.
seems to have something to do with `plate/src/tabs.php` on `line 20`.

commenting it out let me run the setup, but may be worth looking into.

Using WP 4.5.3 & WooCommerce 2.6.3

edit: also running multi site

**Comment by vinkla** [comment]
@nathanaelphilip actually never tried WordPlate with WooCommerce before so it is great that you're testing it out! Could you share the error message with us?

**Comment by nathanaelphilip** [comment]
i didn’t think to grab it. once it “fixed” the issue, i went through the process. it should be pretty easy to replicate, but I’ll let you know if I find anything else.

**Comment by vinkla** [comment]
Okay, good. Let me know if you find anything. 

This is the line you're referring:

https://github.com/wordplate/plate/blob/eb69da07c05a3e5b0fdca59e2f22b968b996dc36/src/tabs.php#L20

**Comment by nathanaelphilip** [comment]
that is correct

**Comment by vinkla** [comment]
Closing this until we find the error message. Thanks for reporting!

**Comment by nathanaelphilip** [comment]
this is the error:

```
Fatal error: Uncaught Error: Call to a member function remove_help_tabs() on null in /srv/users/serverpilot/apps/quarter-ink/public/plugins/plate/src/tabs.php:20 Stack trace: #0 /srv/users/serverpilot/apps/quarter-ink/public/wordpress/wp-includes/plugin.php(525): {closure}('') #1 /srv/users/serverpilot/apps/quarter-ink/public/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php(150): do_action('admin_head') #2 /srv/users/serverpilot/apps/quarter-ink/public/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php(125): WC_Admin_Setup_Wizard->setup_wizard_header() #3 /srv/users/serverpilot/apps/quarter-ink/public/wordpress/wp-includes/plugin.php(525): WC_Admin_Setup_Wizard->setup_wizard('') #4 /srv/users/serverpilot/apps/quarter-ink/public/wordpress/wp-admin/admin.php(168): do_action('admin_init') #5 {main} thrown in /srv/users/serverpilot/apps/quarter-ink/public/plugins/plate/src/tabs.php on line 20
```

**Comment by vinkla** [comment]
Are you sure Wordpress is loaded where the error is thrown?

**Comment by nathanaelphilip** [comment]
yep - you should be able to easily replicate it yourself. just install woocommerce and go through the set up process (where you install WooCommerce pages, etc)

**Comment by vinkla** [comment]
Reopening this for now. Will look into this in the future.

**Comment by puredazzle** [comment]
I think it is because we call the remove help tabs to early because WooCommerce try to add help tabs by themself and it's already cleared. 

See here http://wordpress.stackexchange.com/questions/50723/how-to-remove-help-tabs

I can test it tomorrow and make a PR. Otherwise feel free to test it now and update.

**Comment by puredazzle** [comment]
Made a PR here: https://github.com/wordplate/plate/pull/1

**Comment by vinkla** [comment]
The fix is merged and version 2.1.1 was just released. @nathanaelphilip could you please try again? Remember to run `composer update`!

**Comment by nathanaelphilip** [comment]
we did it!

**Comment by vinkla** [comment]
@nathanaelphilip great! Let us know if there is anything else.
