### ISSUE TITLE
Redirect loop on install when using Laravel Valet

### ISSUE THREAD

**Issue by robbens** [wordplate/wordplate#167]
I'm getting redirected from http://wordplate.dev to http://wordplate.dev/wordpress/wp-admin/install.php and then stuck in a redirect loop.

This is a fresh install with Laravel Valet 2.0.4 on PHP 7.1

**Comment by vinkla** [comment]
Sadly, Laravel Valet doesn't support WordPlate. You can read more about it here: https://github.com/laravel/valet/pull/131 

Create a [`SiteValetDriver`](https://github.com/laravel/valet/pull/131/files#diff-5778e608b48b6c32120485eae52c1455) class in the root of the project and Valet will use that class to support WordPlate. [Use the following class to make it work.](https://github.com/laravel/valet/pull/131/files#diff-5778e608b48b6c32120485eae52c1455)

**Comment by robbens** [comment]
Yup. That was a breeze setting up. Thanks!

Simply add the class mentioned by **vinkla** above to `~/.valet/Drivers`. Boom!
