### ISSUE TITLE
Why not gitignore public/wordpress + themes (Development workflow)

### ISSUE THREAD

**Issue by amenk** [wordplate/wordplate#168]
As I understand it public/wordpress and public/themes is usually installed via composer. So I would both folders to gitignore.

Is there any reason against changing this in the default gitignore as well?

**Comment by amenk** [comment]
Of course custom non-composer themes have to be un-ignored which makes it a bit tricky.
The Magento composer installer faced similar problems and there was a way to auto-add composer-installed plugins to the `.gitignore`.

**Comment by vinkla** [comment]
> Is there any reason against changing this in the default gitignore as well?

We do ignore the WordPress directory in the `.gitignore` file: https://github.com/wordplate/wordplate/blob/fca3546830f52ef8fd7dcd4f008ce793e6b5e8c7/public/.gitignore#L5

I guess most developers build their own custom themes and want to keep them in the repository. But as you say, if anyone install a theme with Composer, then the directory could be ignored.
