### ISSUE TITLE
Guidelines for development/deploy

### ISSUE THREAD

**Issue by colthreepv** [wordplate/wordplate#171]
It would be nice to have a brief howto steps to get a development environment locally. #141

What it seems to work:

 * `composer create wordplate/wordplate <your-folder-name>`
 * `<Have MYSQL up and working>`
 * edit `.env` accordingly (mysql and salt configuration)
 * `cd public`
 * `php -S localhost:8000`

...is this an acceptable development environment?

It would also be nice to have an idea how to deploy with a containerized solution, I can help with that, but I'm no expert of wordpress ecosystem

**Comment by vinkla** [comment]
Hey @colthreepv! Any suggestion is welcome. We'll happily look at any PR you send our way! 

> It would also be nice to have an idea how to deploy with a containerized solution, I can help with that, but I'm no expert of WordPress ecosystem.

If you were to create a Vagrant or Docker helper for WordPlate we could possibly link to it in the documentation. Let us know!
