### ISSUE TITLE
Initialization only with vhost?

### ISSUE THREAD

**Issue by eddiemf** [wordplate/wordplate#179]
Hello! Sorry for the noob question, is it only possible to initialize setting up a vhost? I tried accessing localhost/wordplate/public and it would redirect me to localhost/wordpress/... which doesn't exist. I managed to run it setting up a vhost, but it wasn't clear in any installation step. Did I miss something? Thank you!

**Comment by vinkla** [comment]
> After installing WordPlate, you should configure your web server's document / web root to be the  public directory. The index.php in this directory serves as the front controller for all HTTP requests entering your application - [Laravel](https://laravel.com/docs/5.4#configuration)

**Comment by eddiemf** [comment]
Yeah I figured that out after a while trying to run it, but I could always run laravel accessing project_folder/public (even though I always setup a vhost also), and this instruction you quoted is no where in wordplate's installation guide, maybe consider adding that near the .env configuration step? I don't know if that's really relevant or it's just that I'm a noob, but I think that's a pretty basic step that should be included. Thanks for the help!

**Comment by vinkla** [comment]
Glad it worked out! I've added this in b9a9f02b2929adfff56d026e442eb86c072055d3.
