### ISSUE TITLE
Fatal error: Cannot redeclare __()

### ISSUE THREAD

**Issue by defser** [wordplate/wordplate#180]
Hello,

i have installed wordplate on my server and it works great! the next thing i wanted to do is installing laravel besides wordplate... all went good, merged files like composer etc... but then i got this error:

 Fatal error: Cannot redeclare __() (previously declared in /var/www/vhosts/*****/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:857) in /var/www/vhosts/*****/httpdocs/public/wordpress/wp-includes/l10n.php on line 201

and nothing more or less. how can i solve the duplicate decalration of __() ?

Thanks!

**Comment by defser** [comment]
my composer.json: 

{
    "name": "wordplate/wordplate",
    "description": "A modern WordPress stack. Don't repeat yourself.",
    "keywords": ["wordplate", "wordpress", "boilerplate", "plate"],
    "license": "MIT",
    "require": {
        "php": "^7.0",
        "wordplate/framework": "^5.1",
        "wordplate/plate": "^3.0",
		"laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
	"require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
	"autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://wpackagist.org"
        }
    ],
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
		"post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
		"sort-packages": true,
        "optimize-autoloader": true
    },
    "extra": {
        "installer-paths": {
            "public/mu-plugins/{$name}": ["type:wordpress-muplugin"],
            "public/plugins/{$name}": ["type:wordpress-plugin"],
            "public/themes/{$name}": ["type:wordpress-theme"]
        },
        "wordpress-install-dir": "public/wordpress"
    }
}

**Comment by defser** [comment]
php artisan is working:

php artisan
Laravel Framework 5.4.24

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

**Comment by vinkla** [comment]
It seems like Laravel and WordPress doesn't play along. Why do you want to install Laravel framework in WordPlate?

**Comment by abdusfauzi** [comment]
@defser you might want to check http://framework.themosis.com/ if you're looking for something Laravel+WordPress setup.

**Comment by defser** [comment]
@abdusfauzi, thanks will look into that

**Comment by Osub** [comment]
me too,how solve？ @defser

**Comment by Patrick-DIJ** [comment]
@Osub 
Make sure you include l10n.php before autoload.php

require_once(dirname(__DIR__) . '/web/wp/wp-includes/l10n.php');

require_once(dirname(__DIR__) . '/vendor/autoload.php');
