### ISSUE TITLE
set domain via .env file

### ISSUE THREAD

**Issue by sandrodz** [wordplate/wordplate#182]
One great feature I miss from bedrock is setting domain in .env file.

Using bedrock I didn't have to change urls in db when migrating site from dev env to prod. I simply edited .env file and it automagically worked.

Would be cool to have this in wordplate.

It is as simple as declaring:

https://github.com/roots/bedrock/blob/master/.env.example#L10-L11

https://github.com/roots/bedrock/blob/master/config/application.php#L38-L39

**Comment by vinkla** [comment]
You can actually already do that with WordPlate as well. Please see https://github.com/wordplate/framework/blob/master/src/Application.php#L109

**Comment by vinkla** [comment]
You can use the environment variables`WP_HOME` and `WP_SITEURL`.

**Comment by sandrodz** [comment]
@vinkla how about `WP_MEMORY_LIMIT` ?

**Comment by vinkla** [comment]
Never used it, what does it do?

**Comment by sandrodz** [comment]
It increases memory limit of WP instance.

**Comment by fiskhandlarn** [comment]
@vinkla How about just greping for all `define` calls and shove them into wordplate? This would at least generate fewer github issues. :D

**Comment by sandrodz** [comment]
Yes https://github.com/wordplate/framework/blob/master/src/Application.php#L109 is missing quite some define calls.

**Comment by sandrodz** [comment]
Or something ability to add via .env file something that is not hardcoded `define($anything, env($anything));`

**Comment by vinkla** [comment]
> @vinkla How about just greping for all define calls and shove them into wordplate? This would at least generate fewer github issues. :D

Nah, the list is to long and we don't want to keep track of mainly unused constants.

> Or something ability to add via .env file something that is not hardcoded define($anything, env($anything));

This is actually already possible in the `wp-config.php` file. 
https://github.com/wordplate/wordplate/blob/b639d109edf47a6a9bdc4c00aef6a9285b25db25/public/wp-config.php#L43-L54
