### ISSUE TITLE
Change name of public folder

### ISSUE THREAD

**Issue by njxqlus** [wordplate/wordplate#183]
Hello!
To use worplate we need to customize vhosts. It's impossible on shared hosting. But some shared hosting use next structure: `site_folder/public_html/...`

That's mean, we can put our project to `site_folder` and rename `public` folder to `public_html` and everything will work!

In Root's Bedrock we need to change application config and composer.json.

In Wordplate we also need to change composer.json and we can change `WP_CONTENT_DIR` in `.env` file to something like this: `WP_CONTENT_DIR=\path\to\wordplate\from\root\public_html`.  But it's uncomfortable. 
Maybe you can do some option like `WP_PUBLIC_FOLDER` in `.env` file?

**Comment by vinkla** [comment]
Hey @njxqlus, this is actually already possible if you use the next major version 6.0. [Follow the upgrade guide](https://wordplate.github.io/docs/upgrade-guide#upgrading-from-5-to-6) and then you can name the public directory to whatever you want. Let me know if you've any other questions!
