### ISSUE TITLE
[Feature] Laravel Blade

### ISSUE THREAD

**Issue by vinkla** [wordplate/wordplate#184]
Adding [Laravel Blade](https://laravel.com/docs/5.5/blade) support built into WordPlate framework. This will make it possible to write view files in Blade. Adding a new helper method called `view()` which will accept the name of the view file and render the template. We could even go further, adding [custom directives](https://laravel.com/docs/5.5/blade#extending-blade) for WordPress specific features to simplify how we've write Blade templates in WordPlate.

> Blade is the simple, yet powerful templating engine provided with Laravel. Unlike other popular PHP templating engines, Blade does not restrict you from using plain PHP code in your views. In fact, all Blade views are compiled into plain PHP code and cached until they are modified, meaning Blade adds essentially zero overhead to your application. Blade view files use the `.blade.php` file extension and are typically stored in the `resources/views` directory - [Laravel](https://laravel.com/docs/5.5/blade#introduction)

Work in progress:

- https://github.com/wordplate/wordplate/pull/185
- https://github.com/wordplate/framework/commit/2b12f704c37647b015fcb6f43c013e430fa0085b

---

If you like this idea and would like so see it integrated into WordPlate, please [give this issue a thumb up](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments). If you don't like  this idea, please leave a comment and give this issue a thumb down.

**Comment by jasonsbarr** [comment]
If I could give it 10,000 thumbs ups, I totally would.

**Comment by vinkla** [comment]
We've discussed this internally and decided to recommend the [`ekandreas/bladerunner`](https://github.com/ekandreas/bladerunner) package to add Laravel Blade support in WordPlate.
