### ISSUE TITLE
Using public assets

### ISSUE THREAD

**Issue by bakgat** [wordplate/wordplate#189]
When I move files (svg's, fonts, ...) in themes/wordplate/assets I can not access these.
ie I copy font with mix
```
const theme = 'wordplate';

mix.setResourceRoot('../');
mix.setPublicPath(`public/themes/${theme}/assets`);

mix.js('resources/assets/scripts/app.js', 'scripts')
    .sass('resources/assets/styles/app.scss', 'styles')
    .copy('resources/assets/fonts/conq-carved-one.otf', `public/themes/${theme}/assets/fonts`)
    .version();
```

And in app.scss I have
```
@font-face
{
    font-family : "Carved One";
    src         : url(/themes/wordplate/assets/fonts/conq-carved-one.otf) format("truetype");
}

body
{
    font-family : "Carved One";
}
```

Then i get this error in console;

![](https://puu.sh/ylV29/25dc7666e8.png)

This happens with all files I try to get from assets folder. Except for the app.css and app.js loaded through mix.
How can I fix this?

**Comment by vinkla** [comment]
Actually, you don't have to move the fonts. Laravel Mix will do that for you automagically. Remove this line from your mix file:
```diff
-.copy('resources/assets/fonts/conq-carved-one.otf', `public/themes/${theme}/assets/fonts`)
```

Update the @font-face to use a relative path instead of an absolute one.

```diff
@font-face {
    font-family : "Carved One";
-    src: url(/themes/wordplate/assets/fonts/conq-carved-one.otf) format("truetype");
+    src: url(../fonts/conq-carved-one.otf) format("truetype");
}
```
Let me know how it goes!

**Comment by bakgat** [comment]
Thanks for the help. 😄 
The copying works perfectly. But still the font can't be found.

![](https://puu.sh/ymoYR/3dc49dc468.png)

**Comment by bakgat** [comment]
I just discovered it only happens with WordplateValetDriver... A local valet driver clone, with some extra specifics for our workflow... 😬 
Sorry for that, but thanks anyhow for teaching me some extra thing 😄
