### ISSUE TITLE
Mention Carbon Fields in the documentation

### ISSUE THREAD

**Issue by wujekbogdan** [wordplate/wordplate#190]
In the documentation, you only mention ACF plugin as a solution for custom fields. I'm a big fan of ACF too, but I've discovered [Carbon Fields](https://carbonfields.net/) lately. IMO it's much more powerful, much better written, more developers-oriented plugin than ACF. 

It would be great if you mentioned Carbon Fields too as an alternative to ACF.

**Comment by vinkla** [comment]
Thanks for the suggestion! I haven't used the plugin myself but you're free to submit a pull request in our [documentation repository](https://github.com/wordplate/wordplate.github.io).

**Comment by abdusfauzi** [comment]
@wujekbogdan dope. 👍
