### ISSUE TITLE
Re-open wordplate/multisite for issue or fix?

### ISSUE THREAD

**Issue by abdusfauzi** [wordplate/wordplate#191]
@vinkla hi, can we re-open wordplate/multisite? what does "archived" mean?

**Comment by vinkla** [comment]
The [archived feature](https://github.com/blog/2460-archiving-repositories) is a way to show which projects that are deprecated. Are you using the plugin currently? Did you find any bugs?

**Comment by abdusfauzi** [comment]
@vinkla just 1 bug. it produce double forward-slash after base url. And composer requirement for wordplate/framework.

**Comment by vinkla** [comment]
Okay, I will open it for changes for a day or so but then archive it again. Please submit a pull request against the repo.

**Comment by abdusfauzi** [comment]
@vinkla just want to ask, any reason you keep this warning flag?

![screen shot 2018-01-08 at 14 27 45](https://user-images.githubusercontent.com/1118229/34660852-84568cd0-f480-11e7-80b9-a7f7a9623c28.jpg)

:)

**Comment by vinkla** [comment]
Yes, this is the archived feature. We don’t use the plugin ourselves anymore.
