### ISSUE TITLE
Wordpress (wp-admin) is linking http assets when accessing https

### ISSUE THREAD

**Issue by etienne-dldc** [wordplate/wordplate#192]
Hi ! ✋ 

I want to enable HTTPS on `wp-admin` (it already work on the theme part).

When I access `https://mywp.domain/wordpress/wp-admin`, the page is serve but all assets are in `http` and are blocked by the browser for security reasons (Mixed Content).

I've tried to set in `.env` the `WP_URL=https://mywp.domain` but then `wp-admin` does not load because it was redirected too many times...

If someone know what I'm missing...

**Comment by vinkla** [comment]
Hey ✋ 

We haven't had this issue ourselves but if this is a bug and we would like to hunt it down. Could you please share the contents of your `.env` file?

**Comment by etienne-dldc** [comment]
I don't think the `.env` file is in cause here, because I haven't add anything except the `WP_URL`. The rest is just basic configuration...

**Comment by vinkla** [comment]
Are you running your application behind a proxy such as Cloudflare? I know there has been issue in the past with this. Try adding this snippet to your `wp-config.php` in the top of the file:

```php
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['HTTPS'] = 'on';
}
```
Please let me know how it goes.

**Comment by etienne-dldc** [comment]
It works ! 🎉 
Thanks !
