### ISSUE TITLE
Wordpress doesn't allow to change interface language

### ISSUE THREAD

**Issue by John-Weetaker** [wordplate/wordplate#194]
Hi,
I don't know if it's a normal behavior, the installer doesn't prospose to select any other language, only english is available in the setting.
![wp_issue_lang_crop](https://user-images.githubusercontent.com/18209197/36070937-5519d27e-0f06-11e8-9a09-d2af94458c8b.png)
To resolve this issue add this line 
```PHP 
<?php 
// file: wp-config.php
define('FS_METHOD', 'direct'); 
```
in `wp-config.php`

**Comment by fiskhandlarn** [comment]
@John-Weetaker: You have to add additional languages the same way you [add plugins ](https://wordplate.github.io/docs/plugins) via composer, but from https://wp-languages.github.io/ instead. Merge something like this to your `composer.json`:

```
{
    "require": {
        "koodimonni-language/core-sv_se": "^4.8"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://wp-languages.github.io"
        }
    ],
    "extra": {
        "dropin-paths": {
            "public/languages/": [
                "vendor:koodimonni-language"
            ]
        }
    }
}
```

@vinkla: Should I make a PR for adding this to https://wordplate.github.io/docs/?

**Comment by vinkla** [comment]
@John-Weetaker thanks for reporting the issue!

I've tried installing a new WordPlate application and it seems to work fine for me:

<img src="https://user-images.githubusercontent.com/499192/36072059-4c502112-0f19-11e8-99f5-ae06f773a1ea.png" width="300">

Did you follow our installation guide? Are you using any plugins that might cause this?

---

@fiskhandlarn are you having this issue on new installations as well?

**Comment by puredazzle** [comment]
@vinkla I can confirm that it works as expected for me also. 

@John-Weetaker do you get any log messages if you remove the fs_method line? And does it work as expected if you install a non Wordplate version of WP

**Comment by fiskhandlarn** [comment]
@vinkla I've never even thought about it when installing, I've instead always changed the language after the installation. But I would think that the composer fix above would expose WP to the required/installed language on installation as well. I can try this out tomorrow.

**Comment by John-Weetaker** [comment]
Thank you for your answers !
@fiskhandlarn I've used your solution it's a good alternative .
I think the issue might come from my environment I'm using Docker (https://github.com/John-Weetaker/lamp-docker), a problem of file permissions maybe ?
Anyway, I find it more elegant to add the language in the composer.json file so I chose that solution.
I did not see anything relative to the language setup in the official installation documentation

**Comment by vinkla** [comment]
@John-Weetaker okay, I'll mark this issue as solved.

**Comment by fiskhandlarn** [comment]
@John-Weetaker I think the issue happens whether you run Docker or not. That's the case for me at least.

@vinkla Do you want me to make a PR for adding documentation for adding lang with composer to https://wordplate.github.io/docs/?

**Comment by vinkla** [comment]
@fiskhandlarn yeah, sounds good. We should add it as a new section and also point out the issue when installing WordPress with Docker.

**Comment by fiskhandlarn** [comment]
@vinkla I have no experience using Docker, so I'll leave that for someone else (and I still firmly believe this issue has nothing to do with Docker, since I can reproduce it without Docker). I'll push a PR soon.

**Comment by fiskhandlarn** [comment]
@vinkla I don't have Ruby on my machine, but I', hoping https://github.com/wordplate/wordplate.github.io/pull/4 will work anyway!
