### ISSUE TITLE
Please help me with DB Configuration with Wordpress using WordPlate

### ISSUE THREAD

**Issue by ankurmakadia** [wordplate/wordplate#195]
I have installed wordplate using Composer in localhost. 
It shows me this error:

![image](https://user-images.githubusercontent.com/16324999/36643869-83fcfc52-1a77-11e8-8e55-a9b55ef5c3f4.png)

And after password set to blank in .env file, it redirects to this:
![image](https://user-images.githubusercontent.com/16324999/36643905-f998b654-1a77-11e8-970c-e34b8766afff.png)

Please help me.

**Comment by vinkla** [comment]
It looks like you're running WordPlate from a sub directory on your web server `/wordplate/public`. This isn't possible with WordPlate. Try setting the `public` as the webroot and restart your server.

**Comment by ankurmakadia** [comment]
Thanks for your response. 
Yes, it seems WordPlate is a great stack for future. So I am configuring it. 

As you have mentioned over installation guide:
"After installing WordPlate, you should configure your web server’s document / web root to be the public directory. The index.php in this directory serves as the front controller for all HTTP requests entering your application."

=> If I copy the content from public folder to public_html. Will that work?
Or please guide me exactly how to configure Web root to Public Directory?

Many thanks in advance! :)

**Comment by vinkla** [comment]
It will work fine. The public directory can be named to anything you want.

**Comment by ankurmakadia** [comment]
@vinkla Many thanks for your kind and prompt response. 

Yes, actually I needed your help to understand this one exactly: "you should configure your web server’s document / web root to be the public directory. "
=>
How do I do this one exactly? Can you please help me with the steps to follow to perform this task exactly?

**Comment by vinkla** [comment]
Please see Laravels docs for more information https://laravel.com/docs/5.6

**Comment by ankurmakadia** [comment]
@vinkla 
Yes, wordplate configuration is clear to me. Thanks for your help. 

How can I install Wordplate with the Wordpress theme on Root?
Is it possible to install Wordplate on Local sever too?

**Comment by vinkla** [comment]
Yes, both is possible.

**Comment by vinkla** [comment]
We keep a similar structure to Laravel. I suggest you take a look at Laravels documentation.

**Comment by ankurmakadia** [comment]
@vinkla Thanks for your response. 
For WordPlate installation, is Node.js installation on server is compulsory?

**Comment by vinkla** [comment]
> For WordPlate installation, is Node.js installation on server is compulsory?

No, you don't need Node if you don't want to use it.

**Comment by ankurmakadia** [comment]
@vinkla Thanks for your response. 
Right now I have installed wordplate with Wordpress theme but it shows this URL http://php-ios-android-magento-prestashop-experts.com/wordpress/wp-login.php

and I want to change it to this URL: http://php-ios-android-magento-prestashop-experts.com/wp-login.php

Can you please guide me what do I need to do now?

**Comment by vinkla** [comment]
This is how WordPlate works. Maybe you could add custom rewrite rules in your .htaccess file to update the URLs.

**Comment by ankurmakadia** [comment]
@vinkla 
so do you mean the Wordplate will be on Root and Wordpress will be inside the Wordpress folder?
Can wordpress be in Root with Wordplate?

**Comment by vinkla** [comment]
This is the expected behaviour. It doesn't really matter since it is only visible for the back-office users.
