### ISSUE TITLE
Additional nginx configuration required

### ISSUE THREAD

**Issue by vikingmaster** [wordplate/wordplate#197]
**Steps to reproduce:**
Just created and configured a fresh wordplate project, did vagrant up with this `Homestead.yaml` config:
```
    -   map: plate.test
        to: /home/vagrant/plate/public
```
**The issue:**
When visiting homepage `http://plate.test`, I get redirected to the installation page `/wp-admin/install.php`, which is correct. However nginx tries to find the script in the `public` directory and outputs `No input file specified` to the browser. This is the error in the log:
```
2018/03/14 09:50:11 [error] 28830#28830: *3 FastCGI sent in stderr: "Unable to open primary script: /home/vagrant/plate/public/wp-admin/install.php (No such file or directory)" while reading response header from upstream, client: 192.168.20.1, server: plate.test, request: "GET /wp-admin/install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "plate.test"
```

Is there a workaround for this, so nginx would always run `public/index.php` with all env configs and correctly find the wordpress scripts in `public/wordpress` directory?

**Comment by vinkla** [comment]
Hmm, haven't tried running this with Homestead myself.

@tditlu I know you're using WordPlate with Homestead, do you know what this issue could be?

**Comment by vikingmaster** [comment]
```
server {
    listen 80;
    listen 443 ssl http2;
    server_name .plate.test;
    root "/home/vagrant/plate/public";

    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/plate.test-error.log error;

    sendfile off;

    client_max_body_size 100m;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;


        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }

    ssl_certificate     /etc/nginx/ssl/plate.test.crt;
    ssl_certificate_key /etc/nginx/ssl/plate.test.key;
}

**Comment by tditlu** [comment]
I have started to use Apache in homestead to mimic the live servers as much as possible.
But I will check if i can dig up my old config, when I used ngnix.

**Comment by vinkla** [comment]
@vikingmaster did you manage to solve this issue? If not, have you tried using Apache in Homestead?

**Comment by vikingmaster** [comment]
@vinkla 
Haven't done it yet, however once I do, will post my solution here.  (Or someone else does before me).
Is there something specific about apache config for the boilerplate? And if so, would it be possible to get a sample of such?

**Comment by tditlu** [comment]
I have now tested to reinstall WordPlate with a new homestead box, and I **do** get the same error as you.
But this was **before** i run `vagrant reload --provision` (or `homestead reload --provision` if you have defined the `homestead` [alias](https://laravel.com/docs/5.6/homestead#daily-usage)).
The folder wasn't mounted, you can check if its mounted by ssh into the box with `vagrant ssh` (or `homestead ssh`, see above) & run & `ls -al /home/vagrant`.

I have [attached](https://github.com/wordplate/wordplate/files/1896055/homestead-config.zip) my `Homestead.yaml` file & a script that you can put in `~/Homestead/scripts` that will handle redirection `/wp-admin` traffic to `/wordpress/wp-admin`. (If you look at the `type` parameter in `Homestead.yaml` you will see where i define the script.)

These tests is made with Homestead & **nginx**.

**Comment by vinkla** [comment]
Thanks @tditlu! I'm closing this issue since it seems to be solved.
