### ISSUE TITLE
[Feature request] Installation with flag for Valet

### ISSUE THREAD

**Issue by jpmurray** [wordplate/wordplate#199]
Hello there!

Starting to play with WordPlate, so far, I like it a lot! ;-)

I'm curious, since I've never touched that side of composer, but would it be possible to have, in the end, the option to do, for example, `composer create-project wordplate/wordplate somprojet --with-valet` so the latest version of the valet driver installs in the root by itself?

**Comment by vinkla** [comment]
Hey @jpmurray!

I'm glad you like it! Let me know if you've any other questions!

**Comment by vinkla** [comment]
Hey @jpmurray!

I'm glad you like WordPlate :) 

Thanks for the suggestion. [I've tried getting WordPlate into Valet](https://github.com/laravel/valet/pull/131) without needing to add the local driver class to the root. We could ship WordPlate with the driver but then everyone not using Valet or haven't heard of it will then have an extra file. For now I think we should keep the current structure. [They are working on making this easier in the future.](https://github.com/laravel/valet/pull/492#issuecomment-355328713)

Let me know if you've any other questions!
