### ISSUE TITLE
Super admin by default?

### ISSUE THREAD

**Issue by jpmurray** [wordplate/wordplate#200]
Discovering the `hide-update` plugin while reading your documentation, I kind of felt in love with it. But their documentation says they hide the notification for everyone _except_ `super-admin`.

Now unless I'm mistaken, the super admin role is tied to network install, and creating the first user on a WordPlate install makes it "admin"... Have I missed something here? Because as much as I like it, it's kind of a missed opportunity to put it in the doc and not being able to use it right after! ;-)

**Comment by vinkla** [comment]
Hmm, maybe @gesen (the author of Hide Updates) could answer this question.

**Comment by gesen** [comment]
I think you're right about superadmin only being available on networks. Maybe a better solution for the Hide Updates plugin would be the ability to select which users are going to see the updates, instead of limiting it to a certain role. Pull requests are welcome. :)

**Comment by vinkla** [comment]
> ...instead of limiting it to a certain role.

I agree, that would be handy.

Another cool feature would be to allow different types of updates. For example; I would like to allow patch releases but not major or minor. Maybe this is possible today already?

**Comment by gesen** [comment]
Great idea about what updates to show/hide. Adding this to the wish list. Will try to work on this in the coming weeks.

**Comment by jpmurray** [comment]
Thank you for that @gesen, @vinkla !

As for PR, I'll see what I can do. I haven't dived into WP in just enough for it to be more difficult then I'd like to ;-)
