### ISSUE TITLE
Multisite compatibility

### ISSUE THREAD

**Issue by sandrodz** [wordplate/wordplate#202]
Hi,

I've tried to setup multisite network on an existing page using wordplate.

`WP_ALLOW_MULTISITE` enabled multisite installer under settings, and I've followed through the installer.

I've copied constants to `public/wp-config.php`

<img width="1382" alt="screen shot 2018-04-19 at 4 57 31 pm" src="https://user-images.githubusercontent.com/8479569/38992760-c24c19e4-43f2-11e8-9927-0cc3b0e3d095.png">

After refresh, I'm being redirected to `domain.com/wordpress/` which is blank.

On fresh install WordPlate sets `siteurl` and `home` to `domain.com/wordpress/`

**Comment by vinkla** [comment]
Hmm, I'm not sure. @tditlu maybe you've an idea about this?

**Comment by sandrodz** [comment]
`/wordpress/wp-admin/` works fine.
Network admin area returns 404. As urls are `/wp-admin/network/sites.php` instead of `/wordpress/wp-admin/network/sites.php`

**Comment by tditlu** [comment]
Is this on Nginx or Apache? Is it in development, are you using Valet or Homestead?

**Comment by sandrodz** [comment]
@tditlu thanks for looking in.

I'm using nginx. My config is:
```
server {
    listen       80;
    server_name  dev.at.ge;
    root         /www/$host/public;

    set $upstream php7;
    include /etc/nginx/nginx-wp-common.conf;
}
```

Full config is here: https://github.com/wearede/DevCeption/tree/master/configs/docker/services/webserver/nginx

**Comment by tditlu** [comment]
For multisites in subfolders, i use these rewite rules:
```
rewrite /wp-admin$ $scheme://$host$uri/ permanent;
rewrite ^/(wp-.*)$ /wordpress/$1 last;
rewrite ^/(/.*\.php) /wordpress$1 last;

if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) /wordpress$1 last;
    rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ /wordpress$1 last;
}
```

Try replacing:
```
# Add trailing slash to */wp-admin requests.
rewrite /wp-admin$ $scheme://$host$uri/ permanent;

# Rewrite multisite in a subdirectory '.../wp-.*' and '.../*.php'.
if (!-e $request_filename) {
    rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) $1 last;
    rewrite ^/[_0-9a-zA-Z-]+.*(/wp-admin/.*\.php)$ $1 last;
    rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ $1 last;
}
```
with the above.

**Comment by sandrodz** [comment]
I need config for multisite on subdomain.

**Comment by tditlu** [comment]
Then you only need this part:
```
rewrite /wp-admin$ $scheme://$host$uri/ permanent;
rewrite ^/(wp-.*)$ /wordpress/$1 last;
rewrite ^/(/.*\.php) /wordpress$1 last;
```
This is for multisite in subfolder:
```
if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) /wordpress$1 last;
    rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ /wordpress$1 last;
}
```

**Comment by vinkla** [comment]
Thanks @tditlu! I'm closing this pull requests as it seems to be solved.
