### ISSUE TITLE
Suggestions for Deployment routines?

### ISSUE THREAD

**Issue by ibes** [wordplate/wordplate#204]
Hi there, 

I just try to figure out the next deployment steps. 
As WordPlate builds on composer it makes sense to have a deployment step that pulls the composer packages. 
Do you have any recommandations?
I am just checking out Envoyer from the Laravel Universe and think that that could be it. 

Would be grateful for hints if there are other tools worth checking out that work grate with WordPlate. 

Thanks,

Sebastian

**Comment by fiskhandlarn** [comment]
I personally prefer https://deploybot.com/ over Envoyer. You could also create your own deployment with https://deployer.org/.

**Comment by vinkla** [comment]
I personally use [Fortrabbit](https://www.fortrabbit.com/) for most of my and client websites. 

> This is not your grandma's hosting. fortrabbit is affordable as shared hosting, powerful as VPS hosting and carefree as managed hosting.
