### ISSUE TITLE
Guidelines for deploying on a server

### ISSUE THREAD

**Issue by aurel-fcc** [wordplate/wordplate#206]
Hi,
I created a wordpress site with wordplate and i would like to deploy it on my server in a subdirectory.
Can you please help me by telling me what i need to do to make it work properly.

example url :  - http://example.com/subdirectory/
                       - http://example.com/subdirectory/public
                       - http://example.com/subdirectory/vendor
                       -  http://example.com/subdirectory/.env

I tried to create a .htaccess file to redirect to the public folder but it doesn't work.

Thanks in advance for your advice.

**Comment by aurel-fcc** [comment]
My website works since I added in .env file :

WP_URL=http://example.com/subdirectory/public/
WP_SITEURL=http://example.com/subdirectory/public/

but i can't access to the admin anymore...

**Comment by vinkla** [comment]
Check out the articlebelow about hosting Laravel in a sub directory. It should be a similar setup with WordPlate. Though, I don’t recommend doing this. 

https://laravel-news.com/subfolder-install
