### ISSUE TITLE
laravel mix issue on compile

### ISSUE THREAD

**Issue by lgt** [wordplate/wordplate#207]
Hi,

first of all thank you for this package. Having started to use I face an issue on assets compile with `laravel-mix`. The js is getting compiled without errors. The scrip is quite simple

```js
import $ from 'jquery'

console.log($)

alert('test again')
```

 As the js is getting loaded there is a console error

`Uncaught SyntaxError: Invalid or unexpected token`

If I copy paste the html from DOM and I let it run the error will not occur.

Any idea what can be behind?

**Comment by vinkla** [comment]
I'm glad you like WordPlate. Don't know what your issue might be. The error message doesn't say much. I suggest you open a new issue in the laravel-mix repository.

**Comment by lgt** [comment]
to repeat my self `If I copy paste the html from DOM and I let it run the error will not occur.` is not a laravel-mix issue it lays on wordplate

**Comment by vinkla** [comment]
> Is not a laravel-mix issue this lays on wordplate.

If you don't know what the error is. How can you be sure that it has something to do with WordPlate?

**Comment by vinkla** [comment]
Again, Laravel Mix lays on top of WordPlate. I suggest you open an issue in the Laravel Mix repository. They might be able to help you.

For future issues anywhere on GitHub I urge you to try being more humble and polite as possible. This is the way to go if you want help from people building open-source software for free on the web.

**Comment by lgt** [comment]
Sorry for the input but first of all you did not let this issue to stand for an hour to be analysed by other followers (if I take a look on your issues status everything is closed) and I must say I'm using laravel daily and  I have some experience around with laravel-mix which is a really cool project by the way provided by Jeffrey Way. So for now I will let this project maybe will improve by time

**Comment by vinkla** [comment]
I don't have time for this. I'm locking this issue. 

https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/
