### ISSUE TITLE
Just some praise

### ISSUE THREAD

**Issue by ibes** [wordplate/wordplate#212]
I am just starting to use WordPlate productive and so far it's a lot of fun. 

Also Plate rocks. 

Thanks for providing and maintaining this!

**Comment by vinkla** [comment]
I'm glad you like it @ibes! We would appreciate if you give WordPlate a star or share it on Twitter. Let us know if you've any question or ides to make the framework better!

**Comment by ibes** [comment]
I already stared it on GitHub and have no Twitter - but I will let people know that I enjoy it. 

I am about to start using Beans productive. A theme framework that feels like a good match for WordPlate.
I already started to promote composer driven WP development there and will try to make WordPlate a thing in that small community ;)

https://github.com/Getbeans/Beans
