### ISSUE TITLE
Cleanup with Throw Away Theme

### ISSUE THREAD

**Issue by ibes** [wordplate/wordplate#213]
Hi there,

just stumbled over this animal and that could be an interesting extension:

https://ithemes.com/2016/03/17/how-to-hardcode-the-wordpress-setup-process/

The person who wrote the article suggests to set up a "throw away theme" that is activated after the installation of WordPress via Default_Theme and has the only task to clean stuff -> the WP tagline, the default posts and comments etc. 

After the setup the "throw away" theme can be deleted.

**Comment by vinkla** [comment]
I do like the idea. Though, we want to keep WordPlate as non-biased as possible.

We've discussed internally to add a section of good reading material to the WordPlate documentation and this article should definitely be apart of the list.
