### ISSUE TITLE
PHP notices in editor

### ISSUE THREAD

**Issue by early-reflexions** [wordplate/wordplate#221]
Hello there.

I get a bunch of PHP notices in the new wordpress 5.0 editor using wordplate 7.0 :
`Notice:  Undefined index: path in <b>.../htdocs/wp-includes/l10n.php on line 928`

Seems to be related to this problem : 
https://core.trac.wordpress.org/ticket/45256

Although, when I'm doing a standard wordpress 5.0 install there are no problem, but when I use wordplate there seems to be something missing with the $site_url['path'].

Or am I missing something in the configuration file?

**Comment by vinkla** [comment]
Thanks for reporting! From the ticker you've linked it seems to be related to Gutenberg. Are you planing to use the Gutenberg editor or the classic editor?

**Comment by vinkla** [comment]
I've done some [more reading](https://github.com/WordPress/gutenberg/issues/12670) and this seems to be an issue with Gutenberg. Try installing the Classic Editor and see if that works.

Since there is nothing we can do on our end, I'll go ahead and close this.

**Comment by tditlu** [comment]
https://core.trac.wordpress.org/ticket/46387#ticket
