### ISSUE TITLE
.env not found following 7.0 upgrade

### ISSUE THREAD

**Issue by Avock** [wordplate/wordplate#222]
Hello,

Just upgraded to wordplate 7.0 and it seems make default path to base path broke .env lookup. 

When I try to create new wordplate project, same error is showing

Did I missed something ?

**Comment by vinkla** [comment]
👋 	@Avock did you follow the [upgrade guide](https://wordplate.github.io/docs/upgrade#upgrading-from-6-to-7) for version 7.0?

**Comment by Avock** [comment]
Oh no, didn't see it :/ Only read the release notes. 

But before opening an issue, I checked wp-config of this project which haven't moved for 2 years and tried to create new project which also failed.

**Comment by vinkla** [comment]
> Oh no, didn't see it :/ Only read the release notes.

Sorry for the inconvenience. I've added the link to the upgrade guide now.

> But before opening an issue, I checked wp-config file of this project which haven't moved for 2 years and tried to create new project that also failed.

Hmm, I'm running two WordPlate applications using 7.0 without any issues. Do you get any error messages?

**Comment by Avock** [comment]
Yes, I do `composer create-project wordplate/wordplate`

Then I update the `.env` file with one of working 6.* wordplate version.

On I get : 
> Error establishing a database connection

The wp-config.php not following the upgrade guide

Thanks for your time and help :)

**Comment by vinkla** [comment]
You're right. I've pushed the button a little too early. I've retagged version 7.0 and with the following update:

https://github.com/wordplate/wordplate/blob/57ee8c59b44f3214aefd54d11a005551ab3d6832/public/wp-config.php#L39-L41
