### ISSUE TITLE
Error with WordPress 5.0.2

### ISSUE THREAD

**Issue by pjehan** [wordplate/wordplate#223]
I get this error if I do a fresh install using Wordplate latest version:

> Notice:  Undefined index: path in /var/www/wordplate/public/wordpress/wp-includes/l10n.php on line 919

It seems to be related to not having a wp-content folder in the project...

**Comment by menegain** [comment]
I have the same problem, i add `!empty($content_url['path'])` in the condition line 918 in file wp-includes/l10n.php for resolve the problem but it's not a enduring solution... Another solution ?

**Comment by vinkla** [comment]
Thanks for reporting @pjehan! I've upgraded two applications to the latest version of WordPlate without any issues. Does this issue still occur for you?

**Comment by menegain** [comment]
> Thanks for reporting @pjehan! I've upgraded two applications to the latest version of WordPlate without any issues. Does this issue still occur for you?

The problem occur when we do a fresh install, not an upgrade. This issue occurred today for me.

**Comment by Sander-CabinetC** [comment]
Having this issue too, after a fresh install.
Error message showing in the backend when opening a page with editor.

**Comment by vinkla** [comment]
Hmm, just tried setting up a new WordPlate project locally and it seems to work fine. Have you tried running `composer update` to get the latest WordPress version 5.0.3?

**Comment by vinkla** [comment]
I’m running PHP 7.3.

**Comment by pjehan** [comment]
@vinkla I just tried again and got the same error. I am using PHP 7.2 but I don't think it's related to the PHP version.
It looks like there is a problem with the WP_CONTENT_URL constant declared line 103 in vendor/worplate/framework/src/Application.php
`define('WP_CONTENT_URL', env('WP_CONTENT_URL', WP_HOME));`

If I remove this line, the error disappear and the constant is then declared line 139 in public/wordpress/wp-includes/default-constants.php
`if ( !defined('WP_CONTENT_URL') )
		define( 'WP_CONTENT_URL', get_option('siteurl') . '/wp-content'); // full url - WP_CONTENT_DIR is defined further up`

Do you have a line related to WP_CONTENT_URL in your .env file?
I don't and then the WP_HOME constant is used and it's value is "http://localhost:8001" on my computer and that's why the error in file l10n.php is thrown because there is no path in this URL.

**Comment by puredazzle** [comment]
I am running PHP 7.2.10, latest version of the framework and WP 5.0.3. It work as expected without any notice. @pjehan do you have any other plugins active?

**Comment by pjehan** [comment]
@puredazzle No, I just created a fresh install yesterday without any plugins.

**Comment by vinkla** [comment]
I did some reading and it seems this is an [issue with Gutenberg](https://core.trac.wordpress.org/ticket/45256). Either wait for the WordPress team to fix this or install the classic editor.

**Comment by early-reflexions** [comment]
@pjehan Thanks so much for your input !
I had the same problem and FINALLY fixed it, just by adding

`WP_CONTENT_URL=http://mywebsite.tld/wordpress/wp-content`
to the .env file

Awesome!

**Comment by tditlu** [comment]
https://core.trac.wordpress.org/ticket/46387#ticket
