### ISSUE TITLE
Anyway to get the list of must use plugins?

### ISSUE THREAD

**Issue by jpmurray** [wordplate/wordplate#226]
Using `get_plugins()` returns the list of plugins, but (it seems) it won't get any plugins loaded with the plugin loader (in the `mu-plugins` dir). What would be the correct way to get _all_ activated plugins?

**Comment by vinkla** [comment]
I'll direct this question to @tditlu who knows the ins-n-outs of the must-use plugins loader.

**Comment by tditlu** [comment]
I'm afraid there is no functionality for that, there is no hooks/filters that we can use to inject the plugins loaded by [`PluginLoader.php`](https://github.com/wordplate/framework/blob/master/src/PluginLoader.php), but maybe you could use `get_plugins(WPMU_PLUGIN_DIR)`?

**Comment by jpmurray** [comment]
Using `get_plugins(WPMU_PLUGIN_DIR)` was a good insight, but won't return anything either :(

There is `get_mu_plugins`, but it will also return an empty array: it does not accept parameters, seems it only checks `wp-content/mu-plugin` if I am to believe the docs. I guess one would have to overwrite that function and force it to check the path returned by `WPMU_PLUGIN_DIR` then?

**Comment by jpmurray** [comment]
Wait, looking at `get_mu_plugins` code over the [doc](https://developer.wordpress.org/reference/functions/get_mu_plugins/), it is using `WPMU_PLUGIN_DIR`, so I _should_ be returning the content, no?

**Comment by jpmurray** [comment]
Sorry for spamming 3 comments in a row. For the history, I just wanted to check if a plugin was present or not, and `is_plugin_active` would just not work. This got me checking `get_plugins` and `get_mu_plugins` and then this question. 

Anyway, I finally just digged in `is_plugin_active` code, and it uses `get_option( 'active_plugins', array())`, that indeed return a list of plugins, with relative path to the regular plugin folder. 

Seems I can check my mu-plugin doing `is_plugin_active("../mu-plugins/plugin-folder/plugin.php")`, but trying to get all the plugins like `get_plugins("../mu-plugins/")` still won't do it.

Anyway, since my initial goal is resolved, I'll close the issue, but I felt like adding this information for the sake of anyone else searching in those areas ;-)
