### ISSUE TITLE
Class 'Dotenv\Environment\DotenvFactory' not found on fresh install

### ISSUE THREAD

**Issue by simonhunt** [wordplate/wordplate#228]
I'm getting this error on a fresh install:

```
Fatal error: Uncaught Error: Class 'Dotenv\Environment\DotenvFactory' not found in /Users/simon/Code/exp/wordplate/vendor/illuminate/support/helpers.php:645 Stack trace: #0 /Users/simon/Code/exp/wordplate/public/wp-config.php(65): env('WP_PREFIX', 'wp_') #1 /Users/simon/Code/exp/wordplate/public/wordpress/wp-load.php(42): require_once('/Users/simon/Co...') #2 /Users/simon/Code/exp/wordplate/public/wordpress/wp-blog-header.php(13): require_once('/Users/simon/Co...') #3 /Users/simon/Code/exp/wordplate/public/index.php(37): require('/Users/simon/Co...') #4 /Users/simon/.composer/vendor/laravel/valet/server.php(147): require('/Users/simon/Co...') #5 {main} thrown in /Users/simon/Code/exp/wordplate/vendor/illuminate/support/helpers.php on line 645
```

My guess is that this is related to the release of Laravel 5.8 (and so the Illuminate packages).

In particular, this appears to be related to this file:
vendor/illuminate/support/helpers.php

I'll keep investigating and let you know if I make any progress.

**Comment by simonhunt** [comment]
I think this is probably due to the new Illuminate packages relying upon dotenv version 3 (whereas the older versions of Laravel and Wordplate rely on version 2.5).

Happy to try changing this and seeing if it works. Will issue a pull request if it does.

**Comment by vinkla** [comment]
Thanks for reporting! This was fixed in:
- https://github.com/wordplate/framework/commit/77b0999861086684a0c418ab6343b5301c172b6a
- https://github.com/wordplate/framework/commit/86d40ca349c4d602bfb45a28c2f7e7c5e2fdb048
- https://github.com/wordplate/framework/commit/8f08f68ad4bf38db8a15bb0f7bfa8ad522eafa20

Just released a new version (7.1.0).

**Comment by menegain** [comment]
Hello, i have the problem when i `composer update` to update wordplate to 8.1. I thinks is from : "Updated vlucas/dotenv to symfony/dotenv". An idea to resolve it ?

**Comment by vinkla** [comment]
Hey @menegain, please open a new issue and describe what issue you're having.
