### ISSUE TITLE
Cache Enabler & Content Directory

### ISSUE THREAD

**Issue by oraimbaud** [wordplate/wordplate#229]
Hi, I tried using the [Cache Enabler](https://wordpress.org/plugins/cache-enabler/) plugin. 
Adding `define( 'WP_CACHE', true );` in `wp-config.php` and activating the plugin does not drop in the `advanced-cache.php` file in the content directory. Even by adding it manually does not help. Does it has to do with how the framework manages the content directory? See [this issue](https://wordpress.org/support/topic/wp_content_dir-cache-cache-enabler-dir-not-being-created/).

Thanks for your help!

**Comment by vinkla** [comment]
Hi! Did you try to follow the [potential solutions from the comments](https://wordpress.org/support/topic/wp_content_dir-cache-cache-enabler-dir-not-being-created/)?

**Comment by oraimbaud** [comment]
Hi Vincent, thanks for the quick reply. Yes I did but maybe I'm missing something

**Comment by vinkla** [comment]
Then I've no idea. WordPlate uses the [official way](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#Constants) to change the `wp-content` directory. This is most likely an issue with the Cache Enabler. If you find a solution, please post it in this thread for future reference.
