### ISSUE TITLE
Searching for best practice - active_plugins + settings/options

### ISSUE THREAD

**Issue by ibes** [wordplate/wordplate#230]
Hi there,

I wonder how to best handle plugin activation status while deploying. 

I see the option to define all plugins as must use plugins and that should make sure all plugins are activated after deployment. 
But I am a bit worried that this could be not best practice. 

WordPress has the option to deactivate failing plugins - that should be impossible with MU plugins. But also: if plugins crash that need to be activated the problem is somewhere else. 

Also do you have a good best practice how to force options/settings through code?
I was thinking about a mu plugin that force-set options but that would need to run with every single request to WordPress.
There could be some "update" routine that is triggered after deployment (maybe needs a post-deployment hook or there could be a check "if version lower x, than do this and that" -> than saving version to DB or to configuration)

Using WordPlate feels great so far. Thank you for the work you put in it :)

**Comment by vinkla** [comment]
> WordPress has the option to deactivate failing plugins - that should be impossible with MU plugins. But also: if plugins crash that need to be activated the problem is somewhere else.

The best advice we can give is to only use plugins you know are stable and robust.

> Also do you have a good best practice how to force options/settings through 
code?

If you're asking about plugins I would recommend to check if the plugin functions exist or not using `function_exists` and add options accordingly. If plugin settings are handled with filters you don't need to worry since the unused filters wont trigger any errors.

> Using WordPlate feels great so far. Thank you for the work you put in it :)

Thanks! We're glad you like it :)

**Comment by ibes** [comment]
Thank you for you answer. 

When asking about settings, I am rather asking about stuff like blogdescription, permalink-settings and other things that is saved in the database and would likely be found in the "Settings" menu. 
But the hint to configurate plugins via filters is also helpful. With well written plugins that is often possible. And in that way of organising I want to hide the menu in production anyway.

**Comment by vinkla** [comment]
For permalinks you can use our `plate` plugin includes a [permalink helper](https://github.com/wordplate/plate#plate-permalink).
