### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by damcclean** [wordplate/wordplate#231]
Hi,

In the footer when I create posts or pages, I get this error:

```
<br />
--
  | <b>Notice</b>:  Undefined index: path in <b>/Users/duncan/Sites/stmarycath/public/wordpress/wp-includes/l10n.php</b> on line <b>949</b><br />
  | <br />
  | <b>Deprecated</b>:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in <b>/Users/duncan/Sites/stmarycath/public/wordpress/wp-includes/l10n.php</b> on line <b>949</b><br />
```
I believe this error is caused by something to do with the site url or something. I can't find much more than that online. I wanted to check if this is a WordPlate issue or an issue of something else.

**Comment by fiskhandlarn** [comment]
https://github.com/wordplate/wordplate/issues/221

**Comment by vinkla** [comment]
Thanks for reporting! One of our core developers has fixed this upstream: https://core.trac.wordpress.org/ticket/46387#ticket
