### ISSUE TITLE
Differences and similarities to WPStarter and 

### ISSUE THREAD

**Issue by ibes** [wordplate/wordplate#234]
Hi,

I am happily using WordPlate in one project right now and thinking about integrating it in another big project soon. 
Right now I try to figure out if WordPlate is the option that I should choose and try to compare it with Bedrock and WPStarter. 

Bedrock: https://github.com/roots/bedrock
and
WPStarter: https://github.com/wecodemore/wpstarter/tree/version-3 (Version 3 in beta)

There is already a good comparison between Bedrock and WPStarter that I found + I asked the developer of WPStarter for how it compares to the both - but he did not really know WordPlate. (https://github.com/wecodemore/wpstarter/issues/87)

May I ask you where you see the differences between WordPlate and both other systems?

It seems like all three systems have a similarly long history and are all mature and I try to see clear what the differences in the approaches are.

Thank you a lot for the work that you put in WordPlate!

**Comment by vinkla** [comment]
Hey @ibes, I'm glad that you like working with WordPlate!

That is a good question. What it comes done too is different kind of flavours, [which you've already has stated in a previous discussion](https://github.com/wecodemore/wpstarter/issues/87#issuecomment-485958706). All three frameworks thrive to make the WordPress development experience better. We all want to push the WordPress development forward.

What WordPlate does differently:

- It focus on simplicity and availability.
- It push for new PHP standards and following PHP-FIG.
- It hides most of the logic in `wordplate/framework` which makes it easy for users to update WordPlate (without having to copy/paste code).
- It ships with Laravel Mix support. If a developer doesn't want or have time to learn for example Webpack, Laravel Mix is a great alternative to get started with and it comes with an easy API.
- It ships with [`wordplate/plate`](https://github.com/wordplate/plate#readme) which is a plugin to simplify the administrator dashboard for users. Removing the clutter.
- It doesn't ship with an opinionated theme. Building themes with WordPlate works like any other WordPress project.
- It comes with [must-use plugins](https://wordplate.github.io/#/docs/plugins#must-use-plugins) out of the box.

There you've a few points why we like working with WordPlate. As stated above, most of the WordPress boilerplates and frameworks out there are a good fit. It all comes down to developer preference.
