### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by blakeperdue** [wordplate/wordplate#235]
## Expected Behavior
You can load https://wordplate.github.io/

## Actual Behavior
Network request gives 500 and nothing renders:

Request URL: https://unpkg.com/docute@4/dist/docute.js?v=19.6.13.1326
Request Method: GET
Status Code: 500 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Versions

  - WordPlate:
  - PHP:

**Comment by vinkla** [comment]
Thanks for reporting! Tried it myself without any issues. Could you paste a screenshot?

**Comment by blakeperdue** [comment]
Odd, it's working today :)
