### ISSUE TITLE
Cannot install network because mu-plugin is active

### ISSUE THREAD

**Issue by dbrw** [wordplate/wordplate#240]
## Expected Behavior
On this step of begining [network setup](https://wordpress.org/support/article/create-a-network/#step-3-installing-a-network) I can see the form to start the installation process. 

## Actual Behavior
there is `Warning: Please deactivate your plugins before enabling the Network feature.` error and nothing else.

## Steps to Reproduce the Problem
after initial setup:
  1. edit the `wp-config.php` file to uncomment `define('WP_ALLOW_MULTISITE', env('WP_ALLOW_MULTISITE', true));` line;
  2. go to dashboard > tools > network setup
  3. see the warning there

## Versions

  - WordPlate: plate version 4.1.0 and framework version 7.1.0
  - PHP: 7.3.10

I think the problem is because the mu-plugin `plate/plate.php` been activated. Any best practice to solve this?

**Comment by vinkla** [comment]
Thanks for reporting the issue! 

I haven't personally used the plugin loader with multisite. Maybe @tditlu knows more about this?

**Comment by dbrw** [comment]
As for now, my work around is to rename `mu-plugin` directory before starting the setup then re-rename it to original name after the setup finished.

**Comment by vinkla** [comment]
Have you tried this with a "normal" WordPress setup? Maybe this isn't related to WordPlate.

**Comment by vinkla** [comment]
Just did a quick search and found this: https://core.trac.wordpress.org/ticket/23825

It seems this is the expected behaviour. This is not related to WordPlate. Thanks for reporting though!
