### ISSUE TITLE
Location for project related php/classes/helper functions

### ISSUE THREAD

**Issue by sandrodz** [wordplate/wordplate#245]
Hi,

Is there a standardized location for keeping custom classes or helper methods related to project within wordplate?

I usually do plugins to encapsulate site-data related functionality. But I don't always want it as a plugin. Would you recommend a place for that within wordplate project tree? How to autoload it?

**Comment by vinkla** [comment]
Hi, I usually follow similar pattern to Laravel and Symfony creating a `helpers.php` file in a `src` directory and autoload it using Composer. It depends on how many helper functions I have. If I only have one or two I add them to the `functions.php` file.

**Comment by Grafikart** [comment]
Same thing here with a root namespace to be sure to have no colision. `MyName\my_helper()` in one helper.php. 

I tried many approaches (soberwp/controller, static methods...) and I always come back to this.
