### ISSUE TITLE
 Deprecated: contextual_help

### ISSUE THREAD

**Issue by dimitriBouteille** [wordplate/wordplate#251]
After installing the project, I have the following error in admin : 

` Deprecated: contextual_help est <strong>obsolète</strong> depuis la version 3.3.0 ! Utilisez get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab() à la place. in [...]public\wordpress\wp-includes\functions.php on line 5088`

If I remove  `mu-plugin/plate` the error disappears. Any idea what the problem is?

## Steps to Reproduce the Problem

  1. Install new project with composer create-project wordplate/wordplate
  2. Install Wordpress
  3. And Go in admin

## Versions

  - WordPlate:  ^7.1
  - PHP: 7.2.14
 - Wordpress: 5.4

**Comment by vinkla** [comment]
`wordplate/plate` has been deprecated and I would recommend to use its successor [Administration UI](https://vinkla.com/administration-ui).

What version of `wordplate/plate` are you using?

**Comment by fiskhandlarn** [comment]
This happens when `plate-disable-tabs` is used (which was removed in version 6.0.0): https://github.com/wordplate/plate/blob/36f20a95b798f61d646866db6fefb53653ca1e68/src/disable-tabs.php#L18

**Comment by fiskhandlarn** [comment]
@dimitriBouteille I'm guessing you have upgraded WordPlate rather than installed from scratch ..? Eitherway; make sure that `wordplate/plate` is at least version 6.0.0 and/or remove the theme support for `plate-disable-tabs`, that should do it.

**Comment by dimitriBouteille** [comment]
@fiskhandlarn It's work ! Thank you :)
