### ISSUE TITLE
Custom Type not showing in Nav Menu

### ISSUE THREAD

**Issue by satanasdiabolo** [wordplate/wordplate#255]
## Expected Behavior

On Nav Menu editor in Admin menu, I should have choices to add my custom types to nav menus.
![image](https://user-images.githubusercontent.com/1850524/84019007-07812180-a981-11ea-8b57-70702c766696.png)

## Actual Behavior

I can't see any custom post type elements on Nav Menu editor
![image](https://user-images.githubusercontent.com/1850524/84019045-136ce380-a981-11ea-9f7b-4a9cd3af5caa.png)

## Steps to Reproduce the Problem

  1. Create a custom Post Type with `register_post_type` set `show_in_nav_menus ` to true
  2. Go to `/wp-admin/nav-menus.php`
  3. You should see a new Nav Menu Choice

## Versions

  - WordPlate: 8.1.0
  - PHP: 7.4

**Comment by satanasdiabolo** [comment]
This behavior only occur on the complete menu editor. When editing a menu via the customize interface I have the expected behavior

**Comment by vinkla** [comment]
It’s unlikely this is because of WordPlate. Does it work in a “normal” WordPress environment? Try adding your code to a basic fresh WordPress installation.

**Comment by satanasdiabolo** [comment]
Indeed, on a clear Wordpress install without plugins the menu editor is correct.
So we can close this case.
