### ISSUE TITLE
wp-json 404

### ISSUE THREAD

**Issue by azralth** [wordplate/wordplate#257]
Hi,
I try to use rest api but for some reason when i go to mywebsite.com/wp-json i get a 404 error.

I use last version of wordplate and twentytwenty theme.

Can you help me with this ?

**Comment by vinkla** [comment]
Please share the error message in this issue.

**Comment by azralth** [comment]
Problem solved, it was the plugin "wpackagist-plugin/nietzsche" recommended in documentation that remove API REST
