### ISSUE TITLE
Webpack set images vendor path

### ISSUE THREAD

**Issue by fredmat** [wordplate/wordplate#265]
I'm importing vendor CSS from node_modules, jQueryUI for the example.
The CSS files are loaded correclty with Webpack and vendor images are exported correctly to public/themes/wordplate/assets/images/vendor/...

The problem is that the images path loaded in the page result in a 404 because I see the path/uri is:
https://mydomain.com/images/vendor/... and not https://mydomain.com/themes/wordplate/assets/images/vendor/...

Config is the default Wordplate config, what should I do?

Thanks

**Comment by vinkla** [comment]
There are a lot of information missing in this issue and I don't think this is an issue with WordPlate. We can't help you debug your code but you're free to submit any pull request to fix any issue with the project.
