### ISSUE TITLE
Multisite network with no input specified

### ISSUE THREAD

**Issue by mehdirochdi** [wordplate/wordplate#269]
# I activated multisite network in wordplate
`define('WP_ALLOW_MULTISITE', env('WP_ALLOW_MULTISITE', true));

define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'wordplate.test');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);`
but i can access to network to manage all my websites **i get no input file specified**

**Comment by vinkla** [comment]
This is most likely not an issue with WordPlate. It is probably due to your web server config.

https://wordpress.stackexchange.com/questions/127849/no-input-file-specified-after-enabling-multi-site#comment180502_127849

https://stackoverflow.com/a/6280481

**Comment by mehdirochdi** [comment]
> This is most likely not an issue with WordPlate. It is probably due to your web server config.
> 
> https://stackoverflow.com/a/14578219
> 
> https://stackoverflow.com/a/6280481
> 
> https://wordpress.stackexchange.com/questions/127849/no-input-file-specified-after-enabling-multi-site#comment180502_127849

I use laravel homestead, so i think problem with nginx
