### ISSUE TITLE
More information about Vite?

### ISSUE THREAD

**Issue by liamb13** [wordplate/wordplate#289]
Is there a setting I need to update somewhere?
Running `npm run dev` or simply `vite` starts localhost:3000, but opening that is just a blank page?

**Comment by vinkla** [comment]
Yeah, you're right, you'll need to visit your PHP server.

**Comment by liamb13** [comment]
And Vite updates that? Cool!

**Comment by vinkla** [comment]
> And Vite updates that? Cool!

Yeah :)
