### ISSUE TITLE
Edit User Roles In Configuration

### ISSUE THREAD

**Issue by puredazzle** [wordplate/wordplate#30]
It would be nice if you could specify which user roles that should be supported in the config.php, for more information please see:

http://codex.wordpress.org/Function_Reference/remove_role

**Comment by vinkla** [comment]
@puredazzle How is it going? Have you hade any progress?

**Comment by puredazzle** [comment]
@vinkla no progress yet. But I think there are two possibilities:

1. Modify the HTML in the dropdown with javascript (remove users)
2. Modify the database query for selecting users. Update the query so it skips some IDs and don't fetch the users roles we don't want.

**Comment by vinkla** [comment]
What do you think would be most useful? Personally i think the first one sounds easier to implement.

**Comment by puredazzle** [comment]
Yes, the first option should be enough.

**Comment by vinkla** [comment]
Have you tried this before? Where do we start?

**Comment by puredazzle** [comment]
Yes, I will post an update tomorrow. Working on it now.

**Comment by vinkla** [comment]
Nice. Can't wait!

**Comment by magnus-bergman** [comment]
:+1:

**Comment by vinkla** [comment]
Closing due to lack of interest.
