### ISSUE TITLE
Activate Plugins In Configuration

### ISSUE THREAD

**Issue by vinkla** [wordplate/wordplate#66]
Active installed plugins from the configuration files.

**Comment by rippedspine** [comment]
add_action('admin_init', function () {

    $option_key = 'theme_is_activated_' . config('theme.slug');

    if (!get_option($option_key)) {
        // ----------------------------------------------------
        // Activate installed Plugins.
        // ----------------------------------------------------
        if (!function_exists('get_plugins')) {
            require_once ABSPATH.'wp-admin/includes/plugin.php';
        }

        $installed_plugins = get_plugins();

        if (!empty($installed_plugins)) {
            $activated_plugins = get_option('active_plugins');
            
            foreach ($installed_plugins as $plugin => $value) {
                if (!in_array($plugin, $activated_plugins)) {
                    $activated_plugins[] = $plugin;

                    do_action('activate_plugin', $plugin);
                    update_option('active_plugins', $activated_plugins);
                    do_action('activate_'.$plugin);
                    do_action('activated_plugin', $plugin);
                }
            }   
        }

        // ----------------------------------------------------
        // Set Theme is Activated to True
        // ----------------------------------------------------
        update_option($option_key, 1);
    }
});

**Comment by vinkla** [comment]
Thanks @rippedspine! This has been merged in https://github.com/wordplate/framework/commit/3248f207ce32a678cdb8b853f9598623f13a4acb
