### ISSUE TITLE
Delete Hello World Post and Page

### ISSUE THREAD

**Issue by vinkla** [wordplate/wordplate#72]
It would be cool to delete the default Hello World page and post by default when the theme is activated.

Why doesn't WordPress offer this by default? Does anyone know any downside to this?

**Comment by mikaelmattsson** [comment]
Look at the example [here](https://codex.wordpress.org/Function_Reference/wp_delete_post)
It should be safe to delete the default posts. The id of the posts to be deleted can be hard coded becuse they are allways the same.

**Comment by vinkla** [comment]
Yeah, I though about deleting the posts with an id of one or two.

**Comment by mikaelmattsson** [comment]
Yes, 1 is allways the default post and 2 is allways the default page. However, it is common for people to edit the default page (and maybe the default post) and put in some actual content. So the only time you can really safely do this is directly after wordpress is installed. And if you can do this, would you really want it? The default posts are there for a reason. It puts som context to the terms ”posts” and ”pages” and could be helpful for a client who has never used WordPress before. Also, if you download the boilerplate and start developing a theme, you might think something is wrong when the posts aren't showing up and the menu is gone.

**Comment by vinkla** [comment]
That is true @mikaelmattsson. You make some good points. I'll close this for now.
